ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: monthly
  skip:
    - cargo-fmt
    - cargo-lock-sync
    - alejandra
    - shfmt
    - shellcheck
  submodules: false

default_stages: [pre-commit]
default_install_hook_types: [pre-commit]

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args: [--ignore-words-list=ser]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.37.1
    hooks:
      - id: check-github-workflows

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: nix develop -c cargo fmt --all
        language: system
        files: '(^|/).+\.rs$|(^|/)Cargo\.toml$'
        pass_filenames: false

      - id: cargo-lock-sync
        name: cargo lock sync
        entry: nix develop -c cargo metadata --format-version=1
        language: system
        files: '(^|/)(Cargo\.toml|Cargo\.lock)$'
        pass_filenames: false

      - id: alejandra
        name: alejandra
        entry: nix develop -c alejandra
        language: system
        files: '\.nix$'

      - id: shfmt
        name: shfmt
        entry: nix develop -c shfmt -w
        language: system
        files: '^scripts/.*\.sh$'

      - id: shellcheck
        name: shellcheck
        entry: nix develop -c shellcheck
        language: system
        files: '^scripts/.*\.sh$'
