[package]
name = "waytorandr-wlroots"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "wlroots backend for waytorandr"
repository.workspace = true
readme = "../../README.md"
keywords = ["wayland", "display", "profiles", "randr", "monitor"]
categories = ["command-line-utilities", "config"]

[dependencies]
waytorandr-core = { path = "../core" }
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
anyhow.workspace = true
tracing.workspace = true
