[package]
name = "waytorandr-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Core library for waytorandr"
repository.workspace = true
readme = "../../README.md"
keywords = ["wayland", "display", "profiles", "randr", "monitor"]
categories = ["command-line-utilities", "config"]

[dependencies]
toml.workspace = true
serde.workspace = true
serde_json = "1.0"
anyhow.workspace = true
tracing.workspace = true
thiserror.workspace = true
directories.workspace = true
fs4 = "1.1.0"

[dev-dependencies]
tempfile = "3.10"
